### ISSUE TITLE
Do we want to move this into aepks GH acc?

### ISSUE THREAD

**Issue by gabrielkrell** [jschmitz2/coffee-is-a-core-value#2]
So it can persist in the chapter after we're gone.  See: https://github.com/aepks/

**Comment by jschmitzuprightlaw** [comment]
This is probably a good idea.

**Comment by gabrielkrell** [comment]
Sir switch accounts

**Comment by crow-fisher** [comment]
how do I move it to the aepks gh?

**Comment by gabrielkrell** [comment]
I think you go settings > transfer ownership

**Comment by crow-fisher** [comment]
Can you give me permissions on that repo?

**Comment by gabrielkrell** [comment]
You mean org membership?

**Comment by crow-fisher** [comment]
yeah, i need permissions to create repositories

**Comment by crow-fisher** [comment]
moved.
