### ISSUE TITLE
Is this repo still in use?

### ISSUE THREAD

**Issue by DanielFallon** [jschmitz2/coffee-is-a-core-value#4]
Looks like there are some *mild* security issues with this code base as of now, should we archive this if it's no longer in use?

**Comment by gabrielkrell** [comment]
+1 for archive (or at least turning off bot PRs). Doubt that anyone will ever run this, but could be of historical interest for next ambitious project.

**Comment by DanielFallon** [comment]
I'll go ahead and archive, we can always copy it/unarchive it in the future
